Repository TheSYNcoder/JuCC, pull requests merged in 2021-04, with the labels that each got.

#1 Fixed: linking errors
  .github/workflows/build_tests.yml
  README.md
  docs/README.md
  docs/cpp_guidelines.md
  docs/tech_clangtools.md
  docs/tech_git.md
  src/include/lexer/lexer.h
  src/include/main/jucc.h
  src/lexer/lexer.cpp
  src/main/jucc.cpp
  src/main/main.cpp
  test/lexer/comments.txt
  test/lexer/input.txt
  test/lexer/input_err1.txt
  test/lexer/lexer_test.cpp
  test/main/main_test.cpp
Labels: documentation, enhancement

#3 grammar added
  README.md
  build_support/run_clang_format.py
  src/grammar/grammar.cpp
  src/grammar/grammar.g
  src/include/grammar/grammar.h
  test/grammar/grammar_test.cpp
  test/grammar/grammar_test_0.g
  test/grammar/grammar_test_1.g
  test/grammar/grammar_test_10.g
  test/grammar/grammar_test_11.g
  test/grammar/grammar_test_12.g
  test/grammar/grammar_test_13.g
  test/grammar/grammar_test_14.g
  test/grammar/grammar_test_15.g
  test/grammar/grammar_test_16.g
  test/grammar/grammar_test_17.g
  test/grammar/grammar_test_2.g
  test/grammar/grammar_test_3.g
  test/grammar/grammar_test_3b.g
  test/grammar/grammar_test_4.g
  test/grammar/grammar_test_5.g
  test/grammar/grammar_test_6.g
  test/grammar/grammar_test_7.g
  test/grammar/grammar_test_8.g
  test/grammar/grammar_test_9.g
  test/main/main_test.cpp
Labels: enhancement

#7 bumping llvm to version 11
  CMakeLists.txt
  script/installation/packages.sh
  src/include/grammar/grammar.h
Labels: bug

#8 Update lexer.h to follow the convention JUCC_LOCALNAMESPACE_FILENAME_H
  src/include/lexer/lexer.h
Labels: enhancement

#9 Fixed: Lexer and added more tests
  src/grammar/grammar.cpp
  src/include/lexer/lexer.h
  src/lexer/lexer.cpp
  src/main/main.cpp
  test/grammar/grammar_test.cpp
  test/lexer/comments.txt
  test/lexer/input.txt
  test/lexer/input_err1.txt
  test/lexer/input_err2.txt
  test/lexer/lexer_test.cpp
Labels: bug

#4 Left recursion, Left Factoring, Trie, Unit Tests
  src/grammar/grammar.cpp
  src/include/grammar/grammar.h
  src/include/utils/left_factoring.h
  src/include/utils/left_recursion.h
  src/include/utils/trie/memory_efficient_trie.h
  src/utils/left_factoring.cpp
  src/utils/left_recursion.cpp
  src/utils/trie/memory_efficient_trie.cpp
  test/utils/trie/trie_test.cpp
  test/utils/utils_test.cpp
Labels: enhancement, ready-to-be-squashed

#15 Fix: grammar.g : constrain main function naming
  codecov.yml
  src/grammar/grammar.g
  src/include/lexer/lexer.h
  src/lexer/lexer.cpp
  test/lexer/arithmetic.txt
  test/lexer/lexer_test.cpp
Labels: enhancement

#14 Removed: using Entity
  src/grammar/grammar.cpp
  src/include/grammar/grammar.h
  src/include/symbol_table/symbol_table.h
  src/include/utils/left_factoring.h
  src/include/utils/trie/memory_efficient_trie.h
  src/utils/left_factoring.cpp
  src/utils/trie/memory_efficient_trie.cpp
  test/utils/trie/trie_test.cpp
Labels: bug, help wanted

#17 Add: First and Follow
  codecov.yml
  src/grammar/grammar.cpp
  src/include/grammar/grammar.h
  src/include/utils/first_follow.h
  src/utils/first_follow.cpp
  test/grammar/grammar_test.cpp
  test/grammar/grammar_test_10.g
  test/grammar/grammar_test_11.g
  test/grammar/grammar_test_12.g
  test/grammar/grammar_test_13.g
  test/grammar/grammar_test_14.g
  test/grammar/grammar_test_15.g
  test/grammar/grammar_test_16.g
  test/grammar/grammar_test_17.g
  test/grammar/grammar_test_18.g
  test/grammar/grammar_test_4.g
  test/grammar/grammar_test_5.g
  test/grammar/grammar_test_6.g
  test/grammar/grammar_test_7.g
  test/grammar/grammar_test_8.g
  test/grammar/grammar_test_9.g
  test/utils/utils_test.cpp
Labels: enhancement
