Repository TheSYNcoder/JuCC, pull requests merged in 2021-05, with the labels that each got.

#22 Added: cin and cout tokens to grammar.g
  grammar.g
  src/grammar/grammar.cpp
  src/include/grammar/grammar.h
Labels: bug

#24 Adding $ in constructor
  src/include/parser/parsing_table.h
  test/parser/parser_test.cpp
  test/parser/parsing_table_test.cpp
Labels: needs-immediate-attention

#28 Update README.md
  README.md
Labels: documentation

#31 Parsing Error Detection
  src/include/parser/parser.h
  src/include/parser/parsing_table.h
  src/main/main.cpp
  src/parser/parser.cpp
  src/parser/parsing_table.cpp
  test/parser/parser_test.cpp
  test/parser/parsing_table_test.cpp
Labels: enhancement

#34 Fixed: grammar.g is now ll(1) after left recursion removal and left f…
  grammar.g
Labels: bugfix

#33 LL1 parser fix
  src/include/parser/parser.h
  src/main/main.cpp
  src/parser/parser.cpp
  test/parser/grammar.g
  test/parser/parser_test.cpp
Labels: bugfix, enhancement

#35 Feature: Formatted JSON Parse Tree output
  CMakeLists.txt
  build_support/nlohmann_json_CMakeLists.txt.in
  src/include/parser/parser.h
  src/main/main.cpp
  src/parser/parser.cpp
  test/parser/parser_test.cpp
Labels: enhancement

#36 Treant.js formatted JSON from parse tree representation
  src/include/parser/parser.h
  src/parser/parser.cpp
  test/parser/parser_test.cpp
Labels: enhancement, ready-to-be-squashed

#45 Support for comments in lexer
  src/lexer/lexer.cpp
  src/main/main.cpp
Labels: ready-to-be-squashed

#44 Add: benchmark
  CMakeLists.txt
  README.md
  benchmark/input/benchmark_grammar.g
  benchmark/input/in1.cc
  benchmark/main/jucc_benchmark.cpp
  codecov.yml
Labels: benchmark, ready-to-be-squashed
